version: "3.7"
services:
  database:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
  chat-server:
    build:
      dockerfile: webdriver.DOCKERFILE
      context: ../
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - ../log/:/usr/src/app/log
volumes:
  mysql-data: